version: '3.8'  # Stelle sicher, dass diese Zeile vorhanden ist!

services:
  web:
    build: .
    container_name: django_app
    command: gunicorn --bind 0.0.0.0:8000 coderr_app.wsgi:application
    volumes:
      - .:/usr/src/app
    expose:
      - 8000
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: coderrdb
      POSTGRES_USER: coderruser
      POSTGRES_PASSWORD: coderrpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /home/safashamari/projects/coderr_app/staticfiles:/home/safashamari/projects/coderr_app/staticfiles
      - /home/safashamari/projects/coderr_app/media:/home/safashamari/projects/coderr_app/media
    depends_on:
      - web

volumes:
  postgres_data:
