# Generated by Django 5.1.4 on 2024-12-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerdetail',
            name='offer',
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='business_details',
            field=models.JSONField(blank=True, null=True, verbose_name='Business Details'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='customer_details',
            field=models.JSONField(blank=True, null=True, verbose_name='Customer Details'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('business', 'Business'), ('customer', 'Customer')], max_length=10, verbose_name='User Type'),
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.DeleteModel(
            name='OfferDetail',
        ),
    ]
