# Generated by Django 5.1.4 on 2024-12-21 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0004_offerdetail_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='profile',
            new_name='user',
        ),
    ]
