# Generated by Django 5.1.4 on 2025-01-12 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0014_remove_order_user_order_business_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')], help_text='Rating from 1 (Poor) to 5 (Excellent).')),
                ('description', models.TextField(blank=True, help_text='Optional description or comment for the review.', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the review was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the review was last updated.')),
                ('business_user', models.ForeignKey(help_text='The business user being reviewed.', on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(help_text='The user who wrote the review.', on_delete=django.db.models.deletion.CASCADE, related_name='written_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
